export interface UpiUriParams {
  /** Payee VPA / Virtual Payment Address (e.g. merchant@hdfcbank) */
  pa: string;
  /** Payee Display Name */
  pn: string;
  /** Merchant Category Code (4 digits, e.g. 5411) */
  mc?: string;
  /** Transaction Reference ID (internal unique transaction ID) */
  tr: string;
  /** Transaction Note / Description */
  tn?: string;
  /** Transaction Amount in INR (e.g. '150.00' or 150) */
  am: string | number;
  /** Currency (Default: INR) */
  cu?: 'INR';
  /** UPI URL link for invoice / reference */
  url?: string;
  /** Mode: 00 (Default), 01 (Static QR), 02 (Dynamic QR), 04 (Intent) */
  mode?: '00' | '01' | '02' | '04';
  /** Merchant Order ID / Reference ID */
  tid?: string;
  /** Organization ID / Bank Code */
  orgid?: string;
  /** Minimum amount to pay (for partial payments) */
  mam?: string | number;
  /** Signature / Checksum generated by Acquiring Bank */
  sign?: string;
}

export interface DynamicQrOptions {
  /** Base UPI URI parameters */
  params: UpiUriParams;
  /** Size in pixels (default: 300) */
  size?: number;
  /** Error correction level: 'L' | 'M' | 'Q' | 'H' (default: 'M') */
  errorCorrectionLevel?: 'L' | 'M' | 'Q' | 'H';
  /** Margin around QR code (default: 2) */
  margin?: number;
  /** Brand color hex (default: '#000000') */
  color?: {
    dark?: string;
    light?: string;
  };
}

export interface DynamicQrResult {
  /** Raw NPCI standard UPI URI (upi://pay?...) */
  rawUri: string;
  /** Base64 Data URL (image/png) */
  qrDataUrl: string;
  /** Raw SVG string */
  qrSvg: string;
  /** ASCII terminal representation for debugging */
  qrAscii: string;
  /** Unique Transaction Reference */
  transactionRef: string;
  /** Payee VPA */
  payeeVpa: string;
  /** Amount */
  amount: number;
  /** Currency */
  currency: 'INR';
  /** Expiration timestamp */
  expiresAt: string;
}

export interface IntentLinksResult {
  /** Generic standard UPI intent URI */
  genericUpiUri: string;
  /** Google Pay app deep link (tez://) */
  gpayUri: string;
  /** PhonePe app deep link (phonepe://) */
  phonepeUri: string;
  /** Paytm app deep link (paytmmp://) */
  paytmUri: string;
  /** CRED app deep link (cred://) */
  credUri: string;
  /** BHIM app deep link (bhim://) */
  bhimUri: string;
  /** Web Intent fallback for mobile browsers */
  webIntentUrl: string;
  /** Transaction Reference */
  transactionRef: string;
  /** Amount */
  amount: number;
}
